version: "3.0"
services:
  db:
    container_name: "chat_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7432:5432"
  redis:
    container_name: "redis"
    image: redis:6.0.16-alpine
    ports:
      - "7379:6379"
